/*
 
 Given two strings s and t which consist of only lowercase letters.
 
 String t is generated by random shuffling string s and then add one more letter at a random position.
 
 Find the letter that was added in t.
 
 Example:
 
 Input:
 s = "abcd"
 t = "abcde"
 
 Output:
 e
 
 Explanation:
 'e' is the letter that was added.
 
*/

public class Solution {
    public char findTheDifference(String s, String t) {
        ArrayList<Character> l = new ArrayList<Character>();
        for(int i=0;i<t.length();i++){
            l.add(new Character(t.charAt(i)));
        }
        for(int i=0;i<s.length();i++){
            l.remove(new Character(s.charAt(i)));
        }
        return l.get(0);
    }
}
